spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/skb_test
    username: root
    password: dmfwlfh3rk!@
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  config-location: classpath:mybatis-config.xml

developer:
  environment: staging
  name: g i t h u b 777

external:
  dababase:
    vendor: maria commit test
    name: git repository
    host: https://www.github.com
    port: 3306